// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chirps.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createChirp = `-- name: CreateChirp :one
INSERT INTO chirps (
    id, user_id, body, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, body, created_at, updated_at
`

type CreateChirpParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateChirp(ctx context.Context, arg CreateChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, createChirp,
		arg.ID,
		arg.UserID,
		arg.Body,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllChirp = `-- name: GetAllChirp :exec
SELECT id, user_id, body, created_at, updated_at FROM chirps
ORDER BY created_at DESC
`

func (q *Queries) GetAllChirp(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, getAllChirp)
	return err
}
